commit_message: '[crowdin] new translations in %language% from Crowdin'
append_commit_message: false
files:
  - source: /Remore.WinUI/Strings/en-us.resw
    translation: /Remore.WinUI/Strings/%locale%.resw
