commit_message: 'fix: new translations in %original_file_name% (%original_file_name%) from Crowdin'
append_commit_message: false
files:
  - source: /Remore.WinUI/Strings/en-us.resw
    translation: /Remore.WinUI/Strings/%locale%.resw
